### ISSUE TITLE
Monitoring of the event queue

### ISSUE THREAD

**Issue by mortenwh** [metno/MMS#35]
The following items shall be monitored:

- [ ] Usage of create/update/delete

- [ ] Response time of every component, and total execution time

- [ ] Number of messages in the queue and number of clients

- [ ] status of the consistency of the event queue cluster (to ensure that it is not in a bad state)

**Comment by charlienegri** [comment]
memo: as Espen mentioned in a stand-up, monitoring infrastructure for mms is already in place apparently, done by Siri (we should probably talk/ask more)
